export const LABELS = {
  SIGNUP_TITLE: 'Sign up',
  FIRST_NAME_LABEL: 'First name',
  LAST_NAME_LABEL: 'Last name',
  DOB_LABEL: 'Date of birth',
  EMAIL_LABEL: 'Email',
  PHONE_NUMBER_LABEL: 'Phone number',
  STREET_LABEL: 'Street',
  CITY_LABEL: 'City',
  STATE_LABEL: 'State',
  ZIP_CODE_LABEL: 'ZIP code',
  USERNAME_LABEL: 'Username',
  PASSWORD_LABEL: 'Password',
  SIGNUP_BUTTON: 'Sign up',
  ADDRESS_DIVIDER: 'Address',
  PERSONAL_DETAILS: 'Personal details',
  CREDENTIALS: 'Credentials',
};
